trigger:
- main

pool:
  name: Mylocalagent   # self-hosted agent name

steps:
- task: HCLAppScanOnCloud@2
  inputs:
    AppSecTestService: 'ASoCConnect'
    applications: 'f5199746-677c-4270-8274-2d2791e26036'
    scanname: 'DemoTest'
    scantype: 'dynamic'
    dynamicType: 'DAST'
    scanURL: 'https://demo.testfire.net'
    network: 'public'
